app:
  title: Community Backstage
  baseUrl: https://backstage.gabportela.pro

organization:
  name: Community

backend:
  baseUrl: https://backstage.gabportela.pro
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: https://backstage.gabportela.pro
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

proxy:
  '/argocd/api':
    target: 'http://argocd-server.argocd.svc.cluster.local/api/v1/'
    changeOrigin: true
    # only if your argocd api has self-signed cert
    secure: false
    headers:
      Cookie:
        $env: ARGOCD_AUTH_TOKEN
  '/test':
    target: 'https://example.com'
    changeOrigin: true
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName

scaffolder:
  defaultAuthor:
    name: ":robot: [backstage-bot]"
    email: gportela@valcann.com.br

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, Group, User, Resource, Location, Template, API]
  locations:
    - type: url
      target: https://github.com/pegasus-idp/backstage-app/blob/main/catalog-entities/locations.yaml
    - type: url
      target: https://github.com/pegasus-idp/backstage-app/blob/main/catalog-entities/user/users.yaml

kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: kubernetes.default.svc.cluster.local
          name: eks-servicos-internos
          authProvider: 'serviceAccount'
          skipTLSVerify: false
          skipMetricsLookup: true
